# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59ded8b95d6b6c647e31754e2fea4b816d40c2135638ec199b3e333829aa8f4b286deb9a7dede1eeb46f6f653628104b02bff191965070ddac2175546df43dde

test:
  secret_key_base: b99168a9a088cd5d0b786c48ef96046cf978f9440916bd69251177251924abe1c7182c80e67fe1e2e8823d4c125eb9068b26f6fb2a0ed70a988c563f324343ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
